"""Build GLiNER training data from READY, non-generated Russian corpora.

Strict/default sources:
  * NEREL -- human-written Russian Wikinews, manual nested NER + relations.
  * Collection3 -- real Russian news, manual PER/LOC/ORG NER (PERSON used here).
  * FactRuEval-2016 -- real Russian news, manual NER. Can be fetched from
    Kaggle's CC0 multilingual mirror or the HF mirror.

No text or PII values are generated by this script.  Generic news dates are
never relabelled as birth dates; NEREL BIRTH_DATE/BIRTH_PLACE are created only
from explicit DATE_OF_BIRTH / PLACE_OF_BIRTH relations.
"""
from __future__ import annotations

import argparse
from datetime import datetime, timezone
import json
from pathlib import Path
import re
import sys
from typing import Any, Iterable

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from ru_pii.real_corpus import (
    SOURCES,
    dedupe_splits,
    flatten_factru_payload,
    load_json_file,
    parse_collection3_item,
    parse_factru_bio_item,
    parse_factru_item,
    parse_jayguard_item,
    parse_nerel_row,
    write_corpus,
)
from ru_pii.adapters import parse_serialized

NEREL_REPO = "iluvvatar/NEREL"
FACTRU_REPO = "gusevski/factrueval2016"
COLLECTION3_REPO = "RCC-MSU/collection3"
JAYGUARD_REPO = "just-ai/jayguard-ner-benchmark"
KAGGLE_FACTRU = "constantinwerner/multilingual-ner-dataset"


def _read_jsonl(path: str | Path) -> list[dict[str, Any]]:
    out = []
    with Path(path).open(encoding="utf-8") as fh:
        for line_no, line in enumerate(fh, 1):
            if not line.strip():
                continue
            try:
                row = json.loads(line)
            except json.JSONDecodeError as exc:
                raise ValueError(f"invalid source JSONL line {line_no}") from exc
            if not isinstance(row, dict):
                raise ValueError("source JSONL row must be an object")
            out.append(row)
    return out


def _hub_download(repo: str, filename: str, *, revision: str, cache_dir: str | None, offline: bool) -> str:
    from huggingface_hub import hf_hub_download
    return hf_hub_download(
        repo_id=repo,
        repo_type="dataset",
        filename=filename,
        revision=revision,
        cache_dir=cache_dir,
        local_files_only=offline,
    )


def _resolve_revision(repo: str, *, requested: str | None, offline: bool) -> str:
    if requested:
        return requested
    if offline:
        raise ValueError(f"offline mode requires an explicit revision for {repo}")
    from huggingface_hub import HfApi
    info = HfApi().dataset_info(repo)
    if not info.sha:
        raise RuntimeError(f"could not resolve immutable revision for {repo}")
    return str(info.sha)


def load_nerel(*, revision: str, cache_dir: str | None, offline: bool) -> dict[str, list[dict[str, Any]]]:
    out: dict[str, list[dict[str, Any]]] = {}
    for split in ("train", "dev", "test"):
        path = _hub_download(NEREL_REPO, f"data/{split}.jsonl", revision=revision, cache_dir=cache_dir, offline=offline)
        out[split] = [parse_nerel_row(row, split=split) for row in _read_jsonl(path)]
    return out


def _dataset_label_names(ds_split: Any) -> list[str]:
    feature = ds_split.features.get("ner_tags")
    inner = getattr(feature, "feature", None)
    names = getattr(inner, "names", None)
    if not names:
        raise ValueError("dataset has integer ner_tags but no ClassLabel names")
    return list(names)


def load_collection3(*, revision: str | None, cache_dir: str | None, offline: bool) -> dict[str, list[dict[str, Any]]]:
    from datasets import load_dataset
    kwargs: dict[str, Any] = {"cache_dir": cache_dir}
    if revision:
        kwargs["revision"] = revision
    if offline:
        # datasets honors HF_DATASETS_OFFLINE/HF_HUB_OFFLINE set by caller.
        pass
    ds = load_dataset(COLLECTION3_REPO, **kwargs)
    out: dict[str, list[dict[str, Any]]] = {"train": [], "dev": [], "test": []}
    aliases = {"train": "train", "validation": "dev", "dev": "dev", "test": "test"}
    for src_split, dst_split in aliases.items():
        if src_split not in ds:
            continue
        names = _dataset_label_names(ds[src_split])
        out[dst_split].extend(
            parse_collection3_item(dict(row), split=dst_split, index=i, tag_names=names)
            for i, row in enumerate(ds[src_split])
        )
    if not out["train"]:
        raise RuntimeError("Collection3 train split not found")
    return out


def load_factru_hf(*, revision: str, cache_dir: str | None, offline: bool) -> dict[str, list[dict[str, Any]]]:
    names = {"train": "train_data.json", "dev": "dev_data.json", "test": "test_data.json"}
    out: dict[str, list[dict[str, Any]]] = {}
    for split, filename in names.items():
        path = _hub_download(FACTRU_REPO, filename, revision=revision, cache_dir=cache_dir, offline=offline)
        items = flatten_factru_payload(load_json_file(path))
        out[split] = [parse_factru_item(item, split=split, index=i) for i, item in enumerate(items)]
    return out


def _split_from_name(name: str) -> str | None:
    stem = name.casefold()
    if re.search(r"(^|[_\-.])(train|training)([_\-.]|$)", stem):
        return "train"
    if re.search(r"(^|[_\-.])(val|valid|validation|dev)([_\-.]|$)", stem):
        return "dev"
    if re.search(r"(^|[_\-.])(test|testing)([_\-.]|$)", stem):
        return "test"
    return None


def _looks_russian_filename(name: str) -> bool:
    n = name.casefold()
    return bool(re.search(r"(^|[_\-.])ru([_\-.]|$)", n) or "russian" in n)


def _table_rows(path: Path) -> Iterable[dict[str, Any]]:
    import pandas as pd
    suffix = path.suffix.casefold()
    if suffix == ".csv":
        df = pd.read_csv(path)
    elif suffix == ".parquet":
        df = pd.read_parquet(path)
    elif suffix in {".json", ".jsonl"}:
        df = pd.read_json(path, lines=suffix == ".jsonl")
    else:
        return []
    return df.to_dict(orient="records")


def load_factru_kaggle(*, cache_dir: str | None = None) -> dict[str, list[dict[str, Any]]]:
    """Download the ready Kaggle FactRuEval mirror and convert its RU files.

    kagglehub may use an existing Kaggle credential, but public downloads can
    also work anonymously depending on Kaggle's current policy.
    """
    import kagglehub
    root = Path(kagglehub.dataset_download(KAGGLE_FACTRU, output_dir=cache_dir))
    candidates = [p for p in root.rglob("*") if p.is_file() and p.suffix.casefold() in {".csv", ".parquet", ".json", ".jsonl"}]
    ru = [p for p in candidates if _looks_russian_filename(p.name)]
    files = ru or candidates
    out: dict[str, list[dict[str, Any]]] = {"train": [], "dev": [], "test": []}
    accepted_files = 0
    for path in files:
        split = _split_from_name(path.name)
        if split is None:
            continue
        rows = list(_table_rows(path))
        if not rows:
            continue
        # If the file is multilingual, retain only Russian rows.
        filtered = []
        for row in rows:
            lang = str(row.get("lang", row.get("language", "ru"))).casefold()
            if lang in {"ru", "rus", "russian", "русский", ""} or _looks_russian_filename(path.name):
                filtered.append(row)
        if not filtered:
            continue
        for i, row in enumerate(filtered):
            if "tokens" not in row or "ner_tags" not in row:
                continue
            # Kaggle mirror normally stores string tags; integer labels are not
            # guessed because an incorrect id->label table poisons supervision.
            tags = parse_serialized(row["ner_tags"])
            if isinstance(tags, list) and tags and isinstance(tags[0], int):
                raise ValueError(f"{path.name}: integer ner_tags need an explicit label map; use HF FactRuEval backend")
            out[split].append(parse_factru_bio_item(row, split=split, index=i))
        accepted_files += 1
    if not out["train"] or accepted_files == 0:
        raise RuntimeError("Kaggle mirror downloaded, but RU train/validation/test BIO files were not detected")
    return out


def load_factru(*, backend: str, revision: str | None, cache_dir: str | None, offline: bool) -> tuple[dict[str, list[dict[str, Any]]], str]:
    if backend == "kaggle":
        if offline:
            raise ValueError("--offline is incompatible with Kaggle backend")
        return load_factru_kaggle(cache_dir=cache_dir), "kaggle"
    if backend == "hf":
        if not revision:
            raise ValueError("HF FactRuEval backend requires resolved revision")
        return load_factru_hf(revision=revision, cache_dir=cache_dir, offline=offline), "hf"
    if backend != "auto":
        raise ValueError("unsupported FactRuEval backend")
    if not offline:
        try:
            return load_factru_kaggle(cache_dir=cache_dir), "kaggle"
        except Exception as exc:
            # Do not log source text or row values; only exception class.
            print(f"Kaggle FactRuEval fetch unavailable ({type(exc).__name__}); falling back to HF mirror.", file=sys.stderr)
    if not revision:
        raise ValueError("HF FactRuEval fallback requires resolved revision")
    return load_factru_hf(revision=revision, cache_dir=cache_dir, offline=offline), "hf"


def load_jayguard(*, revision: str, cache_dir: str | None, offline: bool) -> list[dict[str, Any]]:
    from datasets import load_dataset
    if offline:
        raise ValueError("JayGuard optional import currently requires network")
    ds = load_dataset(JAYGUARD_REPO, split="train", revision=revision, cache_dir=cache_dir)
    return [parse_jayguard_item(dict(item), split="train", index=i) for i, item in enumerate(ds)]


def _merge_into(dst: dict[str, list[dict[str, Any]]], src: dict[str, list[dict[str, Any]]]) -> None:
    for split in ("train", "dev", "test"):
        dst[split].extend(src.get(split, []))


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--output", default="data/real", help="canonical JSONL output directory")
    p.add_argument("--cache-dir", default=None, help="download cache directory")
    p.add_argument("--offline", action="store_true", help="use already-cached HF source files only")
    p.add_argument("--factru-backend", choices=["auto", "kaggle", "hf"], default="auto",
                   help="ready FactRuEval source; auto tries Kaggle first, then HF")
    p.add_argument("--skip-collection3", action="store_true", help="omit Collection3 if its redistribution terms are unsuitable")
    p.add_argument("--include-jayguard", action="store_true",
                   help="add real conversational contexts whose PII values were de-identified before public release")
    p.add_argument("--nerel-revision", default=None)
    p.add_argument("--factru-revision", default=None)
    p.add_argument("--collection3-revision", default=None)
    p.add_argument("--jayguard-revision", default=None)
    args = p.parse_args()

    if args.offline:
        import os
        os.environ.setdefault("HF_HUB_OFFLINE", "1")
        os.environ.setdefault("HF_DATASETS_OFFLINE", "1")

    resolved: dict[str, str | None] = {}
    resolved["nerel"] = _resolve_revision(NEREL_REPO, requested=args.nerel_revision, offline=args.offline)
    # Resolve HF fallback revision even in auto mode, but not for an explicitly Kaggle-only run.
    if args.factru_backend != "kaggle":
        resolved["factrueval_hf"] = _resolve_revision(FACTRU_REPO, requested=args.factru_revision, offline=args.offline)
    if not args.skip_collection3:
        resolved["collection3"] = _resolve_revision(COLLECTION3_REPO, requested=args.collection3_revision, offline=args.offline)

    splits: dict[str, list[dict[str, Any]]] = {"train": [], "dev": [], "test": []}
    _merge_into(splits, load_nerel(revision=str(resolved["nerel"]), cache_dir=args.cache_dir, offline=args.offline))
    enabled = ["nerel"]

    if not args.skip_collection3:
        _merge_into(splits, load_collection3(revision=resolved.get("collection3"), cache_dir=args.cache_dir, offline=args.offline))
        enabled.append("collection3")

    factru, factru_backend_used = load_factru(
        backend=args.factru_backend,
        revision=resolved.get("factrueval_hf"),
        cache_dir=args.cache_dir,
        offline=args.offline,
    )
    _merge_into(splits, factru)
    enabled.append("factrueval")

    if args.include_jayguard:
        resolved["jayguard"] = _resolve_revision(JAYGUARD_REPO, requested=args.jayguard_revision, offline=args.offline)
        splits["train"].extend(load_jayguard(revision=str(resolved["jayguard"]), cache_dir=args.cache_dir, offline=args.offline))
        enabled.append("jayguard")

    splits, dropped = dedupe_splits(splits)
    manifest = {
        "schema_version": "real-corpus-v2",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "text_generation_used": False,
        "synthetic_training_rows_expected": 0,
        "enabled_sources": enabled,
        "factrueval_backend": factru_backend_used,
        "resolved_hf_revisions": resolved,
        "kaggle_factru_dataset": KAGGLE_FACTRU if factru_backend_used == "kaggle" else None,
        "source_notes": {name: vars(SOURCES[name]) for name in enabled},
        "dedupe": {"normalized_exact_text_dropped": dropped, "priority": ["test", "dev", "train"]},
        "mapping_policy": {
            "generic_DATE_is_not_DOB": True,
            "generic_location_is_not_private_address": True,
            "generic_ORG_is_not_passport_issuer": True,
            "nationality_is_not_citizenship": True,
            "NEREL_birth_fields_require_explicit_relations": ["DATE_OF_BIRTH", "PLACE_OF_BIRTH"],
        },
        "structured_pii_policy": "passport/card/CVV/PIN/INN/phone/email/document formats are intentionally delegated to deterministic rules unless an approved de-identified corpus is explicitly added",
    }
    audit = write_corpus(args.output, splits, manifest=manifest)
    print(json.dumps({"output": args.output, "enabled_sources": enabled, "audit": audit}, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
